import user from "@/assets/Logo/avatar.png";

export const reviews = [
    // 5-star reviews (8)
    {
        id: 1,
        name: "আহমেদ হাসান",
        role: "E-commerce Owner",
        product: "Bulk SMS Service",
        stars: 5,
        date: "Jan 16, 2024",
        text: "This SMS platform has transformed our customer communication. Our delivery notifications now have 99.9% success rate and customer satisfaction has increased significantly. The bulk SMS feature saves us hours every week.",
        avatar: user.src,
    },
    {
        id: 2,
        name: "ফারহানা ইসলাম",
        role: "Bank Manager",
        product: "Transactional SMS",
        stars: 5,
        date: "Feb 5, 2024",
        text: "Perfect for banking OTP and alerts. The reliability is exceptional - we've had zero complaints about missed OTPs since switching to this service. The API integration was seamless with our core banking system.",
        avatar: user.src,
    },
    {
        id: 3,
        name: "রহিম মিয়া",
        role: "Healthcare Admin",
        product: "Appointment Reminders",
        stars: 5,
        date: "Mar 12, 2024",
        text: "Our no-show rate dropped from 15% to 3% after implementing SMS appointment reminders. The scheduling feature and automatic sending saves our staff countless hours. Highly recommended for healthcare providers.",
        avatar: user.src,
    },
    {
        id: 4,
        name: "শামীম আহমেদ",
        role: "Logistics Director",
        product: "Delivery Notifications",
        stars: 5,
        date: "Apr 8, 2024",
        text: "Real-time delivery tracking SMS has improved our customer experience dramatically. The two-way SMS feature allows customers to confirm receipt or provide delivery instructions. 24/7 support team is excellent.",
        avatar: user.src,
    },
    {
        id: 5,
        name: "তাহসিনা আক্তার",
        role: "Marketing Manager",
        product: "SMS Marketing",
        stars: 5,
        date: "May 10, 2024",
        text: "Our SMS marketing campaigns now achieve 30% higher open rates than email. The segmentation tools and personalization features are fantastic. Analytics dashboard provides valuable insights for optimization.",
        avatar: user.src,
    },
    {
        id: 6,
        name: "সাজিদ করিম",
        role: "Developer",
        product: "SMS API",
        stars: 5,
        date: "Jun 15, 2024",
        text: "As a developer, I appreciate the clean, well-documented API. Integration took just a few hours. The webhook support is robust and the rate limits are generous. SDK libraries for multiple languages work flawlessly.",
        avatar: user.src,
    },
    {
        id: 7,
        name: "নুসরাত জাহান",
        role: "School Principal",
        product: "School Notifications",
        stars: 5,
        date: "Jul 20, 2024",
        text: "Sending emergency alerts and attendance notifications to parents has never been easier. The broadcast feature allows us to reach all parents instantly. Delivery reports give us peace of mind that messages are received.",
        avatar: user.src,
    },
    {
        id: 8,
        name: "ইমরান হোসেন",
        role: "Restaurant Owner",
        product: "Reservation SMS",
        stars: 5,
        date: "Aug 3, 2024",
        text: "Automated reservation confirmations and reminders have reduced no-shows by 40%. Customers love the convenience of SMS confirmations. The platform is cost-effective compared to other services we've tried.",
        avatar: user.src,
    },

    // 4-star reviews (8)
    {
        id: 9,
        name: "রায়হানা চৌধুরী",
        role: "Retail Store Manager",
        product: "Promotional SMS",
        stars: 4,
        date: "Feb 12, 2024",
        text: "Great for sending promotional offers to our loyalty program members. Delivery rates are excellent. Would give 5 stars if the campaign analytics were more detailed and offered more export options.",
        avatar: user.src,
    },
    {
        id: 10,
        name: "মোহাম্মদ আলী",
        role: "Non-Profit Director",
        product: "Donation Alerts",
        stars: 4,
        date: "Mar 8, 2024",
        text: "Perfect for sending donation acknowledgments and campaign updates to our supporters. The non-profit discount is appreciated. Only issue is occasional delay in message delivery during peak hours.",
        avatar: user.src,
    },
    {
        id: 11,
        name: "সাবিহা সুলতানা",
        role: "Travel Agency Owner",
        product: "Booking Confirmations",
        stars: 4,
        date: "Apr 5, 2024",
        text: "SMS confirmations for flight and hotel bookings work well. Customers appreciate the instant updates. Would be perfect if international SMS rates were more competitive for our overseas clients.",
        avatar: user.src,
    },
    {
        id: 12,
        name: "আরিফুল ইসলাম",
        role: "Real Estate Agent",
        property: "Property Alerts",
        stars: 4,
        date: "May 18, 2024",
        text: "Sending property alerts to potential buyers is efficient and effective. The scheduled messaging feature is useful. Mobile app could be more user-friendly - currently using web dashboard mostly.",
        avatar: user.src,
    },
    {
        id: 13,
        name: "নাদিয়া হক",
        role: "Event Planner",
        product: "Event Reminders",
        stars: 4,
        date: "Jun 22, 2024",
        text: "SMS reminders for events and conferences work reliably. Attendees appreciate the updates. Would love more template options and better integration with event management software.",
        avatar: user.src,
    },
    {
        id: 14,
        name: "জুবায়ের আহমেদ",
        role: "Insurance Agent",
        product: "Policy Updates",
        stars: 4,
        date: "Jul 10, 2024",
        text: "Sending policy renewal reminders and claim updates is straightforward. Compliance features are good. Sometimes experience minor delays in delivery confirmation reports.",
        avatar: user.src,
    },
    {
        id: 15,
        name: "ফারিয়া রহমান",
        role: "Gym Owner",
        product: "Membership Alerts",
        stars: 4,
        date: "Aug 5, 2024",
        text: "Membership renewal reminders and class notifications work well. Members engage better via SMS than email. Would appreciate more flexible scheduling options for different time zones.",
        avatar: user.src,
    },
    {
        id: 16,
        name: "তানভীর হাসান",
        role: "Auto Repair Shop",
        product: "Service Updates",
        stars: 4,
        date: "Sep 15, 2024",
        text: "Sending vehicle service updates to customers is efficient. Two-way SMS allows customers to ask questions. International SMS could be more affordable for our foreign clients.",
        avatar: user.src,
    },

    // 3-star reviews (8)
    {
        id: 17,
        name: "রাশেদ করিম",
        role: "Pharmacy Owner",
        product: "Prescription Alerts",
        stars: 3,
        date: "Mar 10, 2024",
        text: "Works decently for prescription pickup notifications. Delivery is generally reliable but occasionally messages are delayed by several hours, which is problematic for time-sensitive alerts.",
        avatar: user.src,
    },
    {
        id: 3,
        name: "লায়লা বেগম",
        role: "Beauty Salon",
        product: "Appointment SMS",
        stars: 3,
        date: "Apr 15, 2024",
        text: "Basic SMS reminders work but the platform lacks advanced features like calendar integration or automatic rescheduling. Support response time could be faster for business-critical issues.",
        avatar: user.src,
    },
    {
        id: 19,
        name: "শাহেদ মোল্লা",
        role: "Courier Service",
        product: "Delivery SMS",
        stars: 3,
        date: "May 5, 2024",
        text: "Delivery notifications work but the platform feels dated compared to competitors. SMS delivery confirmation sometimes takes too long. Could use a mobile app with offline capabilities.",
        avatar: user.src,
    },
    {
        id: 20,
        name: "মেহজাবিন আহমেদ",
        role: "Consultant",
        product: "Client Updates",
        stars: 3,
        date: "Jun 12, 2024",
        text: "SMS for client meeting reminders works adequately. However, character limit is restrictive for detailed messages. Template management could be more intuitive and organized.",
        avatar: user.src,
    },
    {
        id: 21,
        name: "সুমাইয়া ইসলাম",
        role: "Florist",
        product: "Order Confirmations",
        stars: 3,
        date: "Jul 8, 2024",
        text: "SMS order confirmations reach customers most of the time. However, during holiday seasons we experience occasional delivery failures. Pricing is reasonable but not the most competitive.",
        avatar: user.src,
    },
    {
        id: 22,
        name: "রাকিব হাসান",
        role: "Car Rental",
        product: "Booking SMS",
        stars: 3,
        date: "Aug 20, 2024",
        text: "Rental confirmation SMS works but lacks integration with our booking system. Manual entry required for each message. Would prefer more automation options and API endpoints.",
        avatar: user.src,
    },
    {
        id: 23,
        name: "নাফিসা খান",
        role: "Catering Service",
        product: "Event SMS",
        stars: 3,
        date: "Sep 5, 2024",
        text: "SMS for event catering updates functions but interface is not very user-friendly. Learning curve for new staff. Message scheduling works but could be more flexible with timing options.",
        avatar: user.src,
    },
    {
        id: 24,
        name: "আনামুল হক",
        role: "Cleaning Service",
        product: "Service SMS",
        stars: 3,
        date: "Oct 10, 2024",
        text: "Service appointment reminders work but sometimes messages are marked as spam by carriers. Delivery rate could be more consistent. Customer support is helpful but response time varies.",
        avatar: user.src,
    },

    // 2-star reviews (8)
    {
        id: 25,
        name: "শাহীন আহমেদ",
        role: "IT Company",
        product: "System Alerts",
        stars: 2,
        date: "Apr 20, 2024",
        text: "Critical system alert SMS sometimes fail to deliver immediately, which defeats their purpose. API response times can be slow during peak hours. Not reliable enough for mission-critical notifications.",
        avatar: user.src,
    },
    {
        id: 26,
        name: "তাসনিম ফেরদৌস",
        role: "Clinic Manager",
        product: "Medical SMS",
        stars: 2,
        date: "May 5, 2024",
        text: "Unreliable for medical appointment reminders. Several patients reported not receiving messages, leading to missed appointments. Support was unable to resolve the delivery issues consistently.",
        avatar: user.src,
    },
    {
        id: 27,
        name: "মুনতাসির আলম",
        role: "Delivery Service",
        product: "Tracking SMS",
        stars: 2,
        date: "Jun 15, 2024",
        text: "Delivery tracking SMS often delayed by 30+ minutes, making them useless for real-time updates. Customers complain about outdated information. Had to implement a secondary notification system.",
        avatar: user.src,
    },
    {
        id: 28,
        name: "ফাহিমা রহমান",
        role: "Hotel Manager",
        product: "Hotel SMS",
        stars: 2,
        date: "Jul 8, 2024",
        text: "Check-in/out reminders frequently fail to send during weekends and holidays. International guests often don't receive messages. Interface is confusing for staff training.",
        avatar: user.src,
    },
    {
        id: 29,
        name: "নাবিল হোসেন",
        role: "Security Company",
        product: "Alert SMS",
        stars: 2,
        date: "Aug 12, 2024",
        text: "Security alert SMS have inconsistent delivery times - sometimes immediate, sometimes hours late. Can't rely on this for time-sensitive security notifications. Exploring other providers.",
        avatar: user.src,
    },
    {
        id: 30,
        name: "রাইসা ইসলাম",
        role: "Subscription Service",
        product: "Billing SMS",
        stars: 2,
        date: "Sep 5, 2024",
        text: "Payment reminder SMS often marked as spam by carriers. Delivery rate inconsistent across different mobile networks. Analytics don't provide enough detail to troubleshoot issues.",
        avatar: user.src,
    },
    {
        id: 31,
        name: "জিশান আহমেদ",
        role: "Fitness Center",
        product: "Class Alerts",
        stars: 2,
        date: "Oct 10, 2024",
        text: "Class schedule changes via SMS sometimes don't reach all members. No way to confirm if messages were actually delivered to specific numbers. Member complaints increasing.",
        avatar: user.src,
    },
    {
        id: 32,
        name: "নিশাত জাহান",
        role: "Co-Working Space",
        product: "Member SMS",
        stars: 2,
        date: "Nov 15, 2024",
        text: "Member announcements via SMS often fail during business hours. Platform seems to throttle messages without clear notification. Support tickets take days to get response.",
        avatar: user.src,
    },

    // 1-star reviews (8)
    {
        id: 33,
        name: "আদনান মাহমুদ",
        role: "Emergency Service",
        product: "Emergency SMS",
        stars: 1,
        date: "May 3, 2024",
        text: "Failed completely during critical emergency notifications. Messages either delayed by hours or not delivered at all. Unacceptable for any service that requires reliability. Seeking legal recourse for service failure.",
        avatar: user.src,
    },
    {
        id: 34,
        name: "তামান্না রহমান",
        role: "Wedding Planner",
        product: "Event SMS",
        stars: 1,
        text: "Wedding day coordination SMS failed to deliver to multiple guests, causing chaos and confusion. No support available during the event. Lost clients and reputation damage. Complete service failure.",
        date: "Jun 10, 2024",
        avatar: user.src,
    },
    {
        id: 35,
        name: "সাদমান করিম",
        role: "Financial Advisor",
        product: "Investment Alerts",
        stars: 1,
        date: "Jul 5, 2024",
        text: "Market alert SMS consistently delivered hours after critical events. Clients missed important trading opportunities. Platform claims 99.9% delivery but reality is much lower. Misleading advertising.",
        avatar: user.src,
    },
    {
        id: 36,
        name: "নুসরাত জেরিন",
        role: "Tour Operator",
        product: "Tour Updates",
        stars: 1,
        date: "Aug 8, 2024",
        text: "Tour group coordination SMS failed during international trip. Travelers missed meetups and activities. International SMS delivery unreliable despite claims. Refund request denied despite service failure.",
        avatar: user.src,
    },
    {
        id: 37,
        name: "রিয়াদ হোসেন",
        role: "Auction House",
        product: "Bid Alerts",
        stars: 1,
        date: "Sep 12, 2024",
        text: "Bid notification SMS failed during live auction, causing clients to miss bidding opportunities and lose valuable items. No compensation offered. Service completely unreliable for time-sensitive communications.",
        avatar: user.src,
    },
    {
        id: 38,
        name: "জারা ইসলাম",
        role: "Medical Laboratory",
        product: "Test Results",
        stars: 1,
        date: "Oct 15, 2024",
        text: "Critical medical test result SMS delivered to wrong numbers due to platform error. Major privacy breach and regulatory violation. Platform refused to take responsibility. Avoid for any sensitive communications.",
        avatar: user.src,
    },
    {
        id: 39,
        name: "ফাহাদ আহমেদ",
        role: "Legal Firm",
        product: "Court Updates",
        stars: 1,
        date: "Nov 10, 2024",
        text: "Court hearing reminder SMS failed to deliver to clients, resulting in missed court dates and legal consequences. Service completely unreliable for legal notifications. Exploring legal action against provider.",
        avatar: user.src,
    },
    {
        id: 40,
        name: "মাহিয়া রহমান",
        role: "Flight School",
        product: "Flight Alerts",
        stars: 1,
        date: "Dec 5, 2024",
        text: "Flight schedule change SMS never delivered to students, causing missed lessons and financial losses. Weather alert system failed during critical conditions. Dangerous and completely unreliable service.",
        avatar: user.src,
    },
];